### ISSUE TITLE
Meet the bristolfurs team page - change art credit to say "art by <x>" instead of "<x>"

### ISSUE THREAD

**Issue by NennaTheKind** [BristolFurs/bristolfurs-website#9]
Meet the bristolfurs team page - change art credit to say "art by <x>" instead of "<x>" to eliminate confusion over team member names and who drew their profile picture.

**Comment by querkmachine** [comment]
The same code is used for the artwork on the team page and photography elsewhere on the site.

Could something more agnostic (like "Credit:") work?
